CFLAGS+=-O2

EXE=zerofill wordadd bin2iso bincomp brrrip byteshuf byteswap cdpatch ecm fakecrc hax65816 id3point rels screamf subfile uips usfv vb2rip

all:	$(EXE)

clean:
	$(RM) $(EXE) *~ *.o

vb2rip:	vb2rip.o

usfv:	usfv.o

uips:	uips.o

subfile:	subfile.o

screamf:	screamf.o

rels:	rels.o

id3point:	id3point.o

hax65816:	hax65816.o

fakecrc:	fakecrc.o

ecm:	ecm.o

cdpatch:	cdpatch.o

byteswap:	byteswap.o

byteshuf:	byteshuf.o

brrrip:	brrrip.o

bincomp:	bincomp.o

bin2iso:	bin2iso.o

wordadd:	wordadd.o

zerofill:	zerofill.o
